import 'dart:io';

class DirectUploadException implements Exception {
  DirectUploadException(this.statusCode, this.message);
  final int statusCode;
  final String message;

  @override
  String toString() => message;
}

/// Sends file bytes directly to the presigned object-storage URL.
/// FlashX API is never used as a file proxy.
class DirectUploadClient {
  final HttpClient _client = HttpClient()
    ..connectionTimeout = const Duration(seconds: 20);

  Future<void> upload({
    required File file,
    required String method,
    required String url,
    required Map<String, dynamic> signedHeaders,
  }) async {
    final uri = Uri.parse(url);
    final request = await _client.openUrl(method, uri);

    for (final entry in signedHeaders.entries) {
      // Host is generated by HttpClient from the presigned URL.
      if (entry.key.toLowerCase() == 'host') continue;
      final value = entry.value;
      if (value is List) {
        for (final item in value) {
          request.headers.add(entry.key, item.toString());
        }
      } else if (value != null) {
        request.headers.set(entry.key, value.toString());
      }
    }

    final length = await file.length();
    request.contentLength = length;
    await request.addStream(file.openRead());
    final response = await request.close();
    await response.drain<void>();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw DirectUploadException(
        response.statusCode,
        'Không thể tải tài liệu lên kho lưu trữ.',
      );
    }
  }

  void close() => _client.close(force: true);
}
