export default function Home() {
  return <>
<nav><div className="container"><div className="logo">⚡ FlashX</div><div style={{fontSize:'0.9rem',opacity:0.9}}>Tài xế của bạn, khi bạn cần</div></div></nav>
<section className="hero"><div className="container"><h1>Tài xế của bạn, khi bạn cần</h1><p className="tagline">Dịch vụ lái xe uy tín, an toàn. Dành cho chủ xe, doanh nhân, gia đình.</p><p>FlashX cung cấp các dịch vụ lái xe chuyên nghiệp với tài xế được kiểm tra kỹ lưỡng.</p><div className="cta-buttons"><button className="btn btn-primary">Đặt lái xe ngay</button><button className="btn btn-secondary">Tìm hiểu thêm</button></div></div></section>
<section><div className="container"><h2>Ba dịch vụ lái hộ chính</h2><p className="subtitle">Chọn dịch vụ phù hợp với nhu cầu của bạn</p><div className="services-grid"><div className="service-card"><div className="icon">🚗</div><h3>Lái hộ ô tô</h3><p>Tài xế chuyên nghiệp, kinh nghiệm lâu năm. Phù hợp cho chuyến đi dài, công tác.</p></div><div className="service-card"><div className="icon">🏍️</div><h3>Lái hộ xe máy</h3><p>Tài xế có kỹ năng cao. Ideal cho chuyến đi nội thành, giao dịch.</p></div><div className="service-card"><div className="icon">📋</div><h3>Đăng kiểm hộ</h3><p>Hỗ trợ đăng kiểm xe. Tài xế đưa xe đến trạm đăng kiểm theo lịch hẹn.</p></div></div></div></section>
<section><div className="container"><h2>Cách thức hoạt động</h2><p className="subtitle">Đơn giản, nhanh chóng, an toàn</p><div className="steps"><div className="step"><div className="step-number">1</div><h3>Đăng ký / Đăng nhập</h3><p>Tạo tài khoản FlashX</p></div><div className="step"><div className="step-number">2</div><h3>Chọn dịch vụ</h3><p>Lựa chọn dịch vụ phù hợp</p></div><div className="step"><div className="step-number">3</div><h3>Xác nhận tài xế</h3><p>Nhận thông tin tài xế và theo dõi vị trí</p></div><div className="step"><div className="step-number">4</div><h3>Thanh toán an toàn</h3><p>Thanh toán qua ứng dụng</p></div></div></div></section>
<section style={{backgroundColor:'#f9fafb'}}><div className="container"><h2>An toàn &amp; bàn giao</h2><p className="subtitle">Quy trình bàn giao và chứng thực</p><div className="features-grid"><div className="feature"><div className="feature-icon">✓</div><div><h3>Kiểm tra danh tính</h3><p>Tất cả tài xế được xác minh danh tính, bằng lái, bảo hiểm</p></div></div><div className="feature"><div className="feature-icon">✓</div><div><h3>Hình ảnh bàn giao</h3><p>Ghi lại tình trạng xe trước và sau lái</p></div></div><div className="feature"><div className="feature-icon">✓</div><div><h3>GPS theo dõi</h3><p>Bạn có thể theo dõi hành trình xe trực tiếp</p></div></div><div className="feature"><div className="feature-icon">✓</div><div><h3>Ghi âm &amp; video</h3><p>Các chuyến đi có thể được ghi lại để bảo vệ cả hai bên</p></div></div><div className="feature"><div className="feature-icon">✓</div><div><h3>Hỗ trợ 24/7</h3><p>Đội hỗ trợ khách hàng luôn sẵn sàng</p></div></div><div className="feature"><div className="feature-icon">✓</div><div><h3>Bảo hiểm toàn diện</h3><p>Bảo hiểm trách nhiệm bên thứ ba bắt buộc</p></div></div></div></div></section>
<section><div className="container"><h2>Đặt lịch trước</h2><p className="subtitle">Lên kế hoạch trước. Tài xế sẽ chờ bạn vào thời gian hẹn.</p><div className="highlight-box"><h3>📅 Đặt lịch linh hoạt</h3><p>Bạn có thể đặt dịch vụ từ vài giờ đến vài ngày trước. FlashX sẽ sắp xếp tài xế phù hợp.</p></div></div></section>
<section style={{backgroundColor:'#f0f9ff'}}><div className="container"><h2>Dự án thí điểm tại Thanh Hóa</h2><p className="subtitle">Bắt đầu từ Thanh Hóa, mở rộng cả nước</p><div className="highlight-box" style={{backgroundColor:'#dbeafe',borderLeftColor:'#06b6d4'}}><h3>🚀 Thí điểm 2024</h3><p>FlashX đang thực hiện dự án thí điểm tại Thanh Hóa. Nếu bạn muốn tham gia, vui lòng liên hệ.</p></div></div></section>
<section><div className="container"><h2>Bắt đầu ngay hôm nay</h2><p className="subtitle">Tải ứng dụng FlashX và trải nghiệm dịch vụ lái xe an toàn</p><div className="cta-buttons" style={{marginTop:'2rem'}}><button className="btn btn-primary">📱 Tải ứng dụng iOS</button><button className="btn btn-primary">🤖 Tải ứng dụng Android</button></div><p style={{marginTop:'2rem',textAlign:'center',color:'#6b7280',fontSize:'0.9rem'}}>(Ứng dụng hiện đang ở giai đoạn thí điểm. Vui lòng liên hệ để được cấp quyền truy cập.)</p></div></section>
<footer><div className="container"><p style={{marginBottom:'1rem'}}><strong>FlashX</strong> - Tài xế của bạn, khi bạn cần</p><div className="footer-links"><a href="#about">Về chúng tôi</a><a href="#contact">Liên hệ</a><a href="#privacy">Chính sách</a><a href="#terms">Điều khoản</a></div><div className="footer-bottom"><p>📧 Email: info@flashx.vn</p><p style={{marginTop:'1rem'}}>© 2024 FlashX. All rights reserved.</p></div></div></footer>
</>;
}
